### ISSUE TITLE
how can i use std::owner_less in phmap

### ISSUE THREAD

**Issue by Gatsbyoo** [greg7mdp/parallel-hashmap#163]
example:
`std::map<websocketpp::connection_hdl, SessionId, std::owner_less<websocketpp::connection_hdl>>`

**Comment by greg7mdp** [comment]
I don't think it is possible to use a hash container because you couldn't ensure that values that compare equal return the same hash. You could use `phmap::btree_map` though.

**Comment by Gatsbyoo** [comment]
`connection_hdl`it's a weak_ptr, `owner_less` is sorted based on owner. std::map works well.
Maybe you can also offer such an option. :D

**Comment by greg7mdp** [comment]
Yes, it is possible in this case because we don't fall in the supported use case `even if the values of the raw pointers obtained by get() are different (e.g. because they point at different subobjects within the same object)`. You could define your own EQ and HASH classes, or I can provide some later.

**Comment by Gatsbyoo** [comment]
All right, i get it. I'll do that, thank you. 👍
