### ISSUE TITLE
duplicated hash calls

### ISSUE THREAD

**Issue by 251** [greg7mdp/parallel-hashmap#168]
Hi,
I'm playing a little bit with `(parallel_)flat_hash_sets` and just have two questions:

1) Why do they call the `hash` function twice on insertion (opposed to `unordered_set`)? This seems wasteful. E.g. just adding a print statement above https://github.com/greg7mdp/parallel-hashmap/blob/0e4997324b1369abd07c9660e603b04d81d24776/examples/hash_std.h#L29 gives:
```
using my hash: John
using my hash: John
using my hash: Jane
using my hash: Jane
using my hash: Jane
using my hash: Jane
 ```
whereas an `unordered_set` gives:
```
using my hash: John
using my hash: Jane
using my hash: Jane
```

2) I tried to start with a simple example but whereas `unordered_set` is able to pick up my hash specialisation `phmap` is not. Do I miss sth. (sorry if it is sth. stupid)?

```C++
#include "parallel_hashmap/phmap.h"
#include "parallel_hashmap/phmap_utils.h"

#include <iostream>
#include <unordered_set>

class Foo {
public:
    int a, b, c;

    bool operator==(const Foo &f) const {
        return a == f.a && b == f.b && c == f.c;
    }
};


namespace std {

template<> struct hash<Foo> {
    std::size_t operator()(const Foo &f) const {
        std::cout << "use my hash\n";
        return phmap::HashState().combine(0, f.a, f.b, f.c);
    }
};

template<> struct hash<Foo*> {
    std::size_t operator()(const Foo *f) const {
        std::cout << "use my ptr hash\n";
        return std::hash<Foo>{}(*f);
    }
};

} // std

int main(void) {
    phmap::parallel_flat_hash_set<Foo*> pset;
    std::unordered_set<Foo*> uset;

    Foo f{0,8,15};

    // does not pick up hash
    pset.insert(&f);

    // picks up hash
    uset.insert(&f);
}
```

**Comment by greg7mdp** [comment]
Hey Frank, thanks for submitting the issue, really appreciate it. Both questions are good questions. The second issue is because phmap has a Hash specialization for all pointer types [here](https://github.com/greg7mdp/parallel-hashmap/blob/0e4997324b1369abd07c9660e603b04d81d24776/parallel_hashmap/phmap_utils.h#L168-L169), but I should make sure an override such as the one you are doing works.

I'll look into the duplicated hash calls as well.

**Comment by greg7mdp** [comment]
Hi @251 , I just checked for the double hash, and this happens only in the Debug builds (because of this [assert](https://github.com/greg7mdp/parallel-hashmap/blob/267fc4ddc87eaa6bc6fbc5f8c3a8dba377aae778/parallel_hashmap/phmap.h#L2221-L2223)). So I don't think it is a big issue unless it makes your debug builds too slow.

**Comment by greg7mdp** [comment]
Hi @251 , I fixed your second issue too, please try the latest github code. Thanks again!

**Comment by 251** [comment]
Hi @greg7mdp,

> and this happens only in the Debug builds (because of this [assert](https://github.com/greg7mdp/parallel-hashmap/blob/267fc4ddc87eaa6bc6fbc5f8c3a8dba377aae778/parallel_hashmap/phmap.h#L2221-L2223)).

`assert`s are unrelated to debug builds (try `-O3 -g0`), I guess I have to disable them for phmap.

> I fixed your second issue too, please try the latest github code

It works now! Thanks for fixing it.

**Comment by greg7mdp** [comment]
You are right, maybe that check is excessive. I'll disable it unless especially requested.
