### ISSUE TITLE
Missing `front()`, `back()` in Btree containers

### ISSUE THREAD

**Issue by HolyBlackCat** [greg7mdp/parallel-hashmap#177]
A minor issue: Btree containers lack `front()` and `back()` methods (returning references to first and last elements respectively), that their `std::` counterparts do have.

**Comment by HolyBlackCat** [comment]
My bad, `std::set` doesn't have those too... Strange.

**Comment by greg7mdp** [comment]
I think because the standard differentiates `sequence` and `associative` containers, and only `sequence` containers have `front`/`back`.  Maybe because with a vector you know when you change the `front` or `back`, with `push_back()` for example, while with an associative container the insertion of any element may change the `front` or `back`.

**Comment by greg7mdp** [comment]
Thank you for the comment anyways @HolyBlackCat !
