### ISSUE TITLE
max_load_factor() does not work properly.

### ISSUE THREAD

**Issue by Austin1511** [greg7mdp/parallel-hashmap#29]
When I run following code:
```
phmap::parallel_flat_hash_map<std::string, int> my_map;
my_map.max_load_factor(0.5);
my_map.reserve(15);
std::cout << my_map.max_load_factor() << std::endl;
std::cout << my_map.bucket_count() << std::endl;
```
I got the result:
```
1
16
```
But it is supposed to be:
```
0.5
32
```

**Comment by greg7mdp** [comment]
Calling `max_load_factor(float)` does nothing in phmap, because the hash map is designed to be efficient under a high load factor, and decreasing it would not only increase memory usage, but also decrease performance as well. It is not clear why anyone would want that. the API is just present for compatibility.

**Comment by greg7mdp** [comment]
Also, because phmap is an open-addressing implementation (no buckets), the load factor cannot be greater than 1. So max_load_factor() always return 1, because the load factor can actually be 1 for maps with 1 or 3 entries, and stays below 0.875 for larger maps.

**Comment by Austin1511** [comment]
Thank you for the answer and your great work! @greg7mdp
