### ISSUE TITLE
phmap btree_map strange behavior

### ISSUE THREAD

**Issue by mr-eyes** [greg7mdp/parallel-hashmap#43]
Hi @greg7mdp , thanks for this amazing chain of powerful projects.

I'd like to ask about the behavior of the **phmap::btree_map** and I have several inquiries.

Sorry if this seemed to be _unprofessional_ documenting of the issue but I could not find a better way to describe, so I recorded a short video.

![ezgif-6-17801bba0096](https://user-images.githubusercontent.com/7165864/76855043-f54b8780-6858-11ea-8e1e-a4a3a7570749.gif)

Or view it from the following [URL](https://streamable.com/n1g5h).

As you will see, there's inconsistency in the output of compiling and running the same code.

The code used:

1. main.cpp

```c++
#include <iostream>
#include <map>
#include <cstdint>
#include <parallel_hashmap/btree.h>

int main(){
    std::cout << "phmap btree Inserting uint64_t ..." << std::endl; 
    phmap::btree_map<uint64_t, uint64_t> btree_1;
    for(uint64_t i; i < 10000; i++) btree_1[i] = i;
    std::cout << "btree_1 size: " << btree_1.size() << std::endl << std::endl;

    std::cout << "phmap btree Inserting int ..." << std::endl; 
    phmap::btree_map<int, int> btree_2;
    for(int j; j < 10000; j++) btree_2[j] = j;
    std::cout << "btree_2 size: " << btree_2.size() << std::endl << std::endl;
}
```

2. CmakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.4)
project(btree_map_issue)


set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -fPIC -fopenmp -W -Wall -pedantic -O3 -oFast")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -Wall")


file(GLOB SOURCES 
"main.cpp"
)

include_directories(parallel-hashmap)
add_executable(run_issue ${SOURCES})
```

Thank you.

**Comment by greg7mdp** [comment]
Hi @mr-eyes ,

Thanks for the well documented report. I really liked the video :-)

The issue is with your test program though , because you do not initialize the variables i and j in the loops. Maybe you are familiar with another language where automatic variables are automatically initialized to 0, but it is not the case for c++.

So for example when j starts the loop with a random value greater than 1000, it takes a long time incrementing it one by one till it reaches the maximum value of MAX_INT which is around 2 billion, and then runs through all the negative numbers to get back to 1000.

Here is the correct program:

```
#include <iostream>
#include <map>
#include <cstdint>
#include <parallel_hashmap/btree.h>

int main(){
    std::cout << "phmap btree Inserting uint64_t ..." << std::endl; 
    phmap::btree_map<uint64_t, uint64_t> btree_1;
    for(uint64_t i = 0; i < 10000; i++) btree_1[i] = i;
    std::cout << "btree_1 size: " << btree_1.size() << std::endl << std::endl;

    std::cout << "phmap btree Inserting int ..." << std::endl; 
    phmap::btree_map<int, int> btree_2;
    for(int j = 0; j < 10000; j++) btree_2[j] = j;
    std::cout << "btree_2 size: " << btree_2.size() << std::endl << std::endl;
}
```

Thanks for using phmap. Be sure to let me know what is your experience with it. Thanks - greg

**Comment by mr-eyes** [comment]
OMG! I really have no idea how did I miss that! it's an ABC C++ basics.
Thanks @greg7mdp for your time and detailed reply and I'm glad that you liked the video though :-)

Thank you,
