### ISSUE TITLE
slow than unordered_map

### ISSUE THREAD

**Issue by jyouAc** [greg7mdp/parallel-hashmap#7]
I run the examples/emplace.cc and i found the phmap::flat_hash_map slower than unordered_map, is that something wrong?

here is the output

bench: iterations: 100000 / container_size: 1
  std::unordered_map:     178 ms
  std::map:               120 ms
  std::vector<std::pair>: 118 ms
  phmap::flat_hash_map:   541 ms
bench: iterations: 100000 / container_size: 10
  std::unordered_map:     1300 ms
  std::map:               1461 ms
  std::vector<std::pair>: 802 ms
  phmap::flat_hash_map:   3574 ms
bench: iterations: 100000 / container_size: 50
  std::unordered_map:     8307 ms
  std::map:               9969 ms
  std::vector<std::pair>: 5532 ms
  phmap::flat_hash_map:   19734 ms

my g++ version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

**Comment by greg7mdp** [comment]
Thanks for reporting this, and sorry about that! The slower time was because the cmake confix file did not build the examples with optimization on (flag -O3). I have fixed this in CMakeLists.txt. Now the time for the phmap::flat_hash_map is a little bit faster than the std::unordered_map.

**Comment by greg7mdp** [comment]
Also, because the values inserted contain strings, most of the time was spent allocating memory for the values, which is why the different tables don't show much difference. Even adding the values to a vector is slow.

I will check in an updated `emplace.cc` tomorrow, which adds a second series of tests with values not containing strings. This allows to see the actual speed difference between the different hast tables.
