### ISSUE TITLE
btree support question

### ISSUE THREAD

**Issue by jmbnyc** [greg7mdp/parallel-hashmap#93]
Greg,
I see that the btree's in this project are a direct port (with modifications from abseil) and was wondering how you are updating your port, e.g. are you tracking changes and ensuring that any bug fixes or improvements are also applied to the btree's in this project?

**Comment by greg7mdp** [comment]
I am tracking changes from time to time, applying those I feel are necessary. This is already a high quality, battle worn implementation so I don't believe any serious bugs lurk in there. I have used it myself at work (and the hash maps as well) with zero problems. I enjoy having both high performance btree map/set and hash sets/maps available in one single location.
If there was a serious issue fixed in Abseil that someone alerted me about, I would certainly merge it.

**Comment by jmbnyc** [comment]
Perfect. I was very happy to see your ports because I've been using the original btree map/set code that google released and then abandoned. I noted that they redid it for abseil but I don't want abseil (just like I don't want boost) because it is too massive. Your header only impls are perfect for my usage and thus I want to update the btree's to your ports.

**Comment by greg7mdp** [comment]
Yes, I used those as well. The Abseil/phmap version supports the C++11 hoodies like emplace, moves, etc... which is very nice.

**Comment by jmbnyc** [comment]
Absolutely, have been bothered that the originals did not support emplace and move semantics. BTW, your parallel hash map is also interesting to me. I have my own lock free hash map that is super optimized but it takes a different approach to get resize scalability. First, it does a parallel resize using a thread pool but also forces any finder/erase/inserter that arrives during the resize to help the resize so instead of sleeping or spinning they help get it done. This works fairly well. However, another thought was to go the same route as what you have done and do a lock free map that is an array of lock free hash maps. Our stuff does well for about 500M keys but resize beyond that starts to get ugly.

**Comment by greg7mdp** [comment]
The parallel hashmaps resize are not nearly as bad, because typically the submaps do not resize at the same time. Normally, when you resize the array to double the size, you have a peak memory of 3x the size (goes back to 2x when original array is freed). This does not typically occur with parallel hashmaps (much lower peak memory requirement). basically the parallel hash maps implement the "array of lock free hash maps" you suggest.

**Comment by jmbnyc** [comment]
Agreed which is why I say beyond 500M it gets ugly because you have to hold onto the memory and thus breaking up the problem as you have done is an excellent way to solve the problem. Yes, I have read your write up. My use case requires no locking in the find path which is what my lock free hash map achieves. Thus, doing a parallel hash map on top of my lock free hash map is probably something I will investigate because we have some users that are planning > 500M unique keys.
