### ISSUE TITLE
Consider renaming to avoid confusion

### ISSUE THREAD

**Issue by ssylvan** [greg7mdp/parallel-hashmap#98]
For better or worse, the word "parallel" is almost always used to refer to multi-threading. A parallel hashmap sounds to me like either a concurrent hash map, or some kind of data parallel hash map (again, in the mult-threading sense). That's not what this is, though, so there's a risk of confusion. 

Also, even when you're using "parallel" in the sense of talking about multiple parallel containers, at least for me that implies that the containers are all the same size and indexed with the same key. E.g. two parallel arrays means two arrays of the same size where the elements in each array for a given index are in some way connected. That's not the way the term is used here. So IMO even without the multi-threading confusion, the name isn't super clear (but the multi-threading confusion is really the key issue here).

Maybe try something like sharded hash maps? Or split hash maps? Or subdivided hashmaps?

**Comment by greg7mdp** [comment]
The parallel hashmaps can be used advantageously in a multi-thread context, so the name doesn't seem to me to be completely inappropriate. I do agree with you though that _parallel-hashmap_ was probably not the best choice for a name. I often wish I had just used _phmap_.

However, I feel it is too late to change the name now, and since I am the benevolent dictator of this repo, I'll leave the name as it is.
